### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pypingou** [AddToCalendar/addtocalendar#1]
There is no license provided for the code available on this repository, have you chose one?

**Comment by atc-master** [comment]
It's MIT licence now.

**Comment by pypingou** [comment]
Where can it be found? (beside on this ticket)

**Comment by atc-master** [comment]
https://github.com/AddToCalendar/addtocalendar-bower-package/blob/master/LICENSE

**Comment by pypingou** [comment]
Shouldn't be added to every projects? Or have the projects indicate where the code lays?
