### ISSUE TITLE
Description has http://go.addtocalendar.com in it

### ISSUE THREAD

**Issue by elie222** [AddToCalendar/addtocalendar#17]
Why does the description automatically add:

`http://go.addtocalendar.com`

to the end of it?

**Comment by thoughtpalette** [comment]
^ That's pretty damn sneaky.

**Comment by thoughtpalette** [comment]
I've sent them an email regarding this issue.

**Comment by measureddesigns** [comment]
+1

**Comment by RyanMadsen** [comment]
+1

**Comment by akhildave** [comment]
+1

**Comment by jamesonnuss** [comment]
+1

**Comment by birdspider** [comment]
I to just stumbled upon this and it worries me, I seems that the links it produces i.e.

```
http://addtocalendar.com/atc/google?utz=60&uln=en&vjs=1.5&e[0][date_start]=2016-11-30%2000%3A00%3A00&e[0][date_end]=2016-12-03%2011%3A00%3A00&e[0][timezone]=Europe%2FBerlin&e[0][title]=some%20title&e[0]
[description]=some%20descr&e[0][location]=somewhere
```

get ping-ponged to http://addtocalendar.com/atc/google - which I presume prepare a special calendar-target specific redirect 

like so:

(check out the Location Header - there is the  `--%0Ahttp%3A%2F%2Fgo.addtocalendar.com` text)

```
curl -v -e 'http://www.google.at' 'http://addtocalendar.com/atc/google?utz=60&uln=en&vjs=1.5&e\[0\_start\]=2016-11-30%2000%3A00%3A00&e\[0\]\[date_end\]=2016-12-03%2011%3A00%3A00&e\[0\]\[timezone\]=Europe%2FBerlin&e\[0\]\[title\]=some%20title&e\[0\]\[location\]=somewhere&e\[0\]\[description\]=somedesc2'
*   Trying 35.162.86.54...
* TCP_NODELAY set
* Connected to addtocalendar.com (35.162.86.54) port 80 (#0)
> GET /atc/google?utz=60&uln=en&vjs=1.5&e[0][date_start]=2016-11-30%2000%3A00%3A00&e[0][date_end]=2016-12-03%2011%3A00%3A00&e[0][timezone]=Europe%2FBerlin&e[0][title]=some%20title&e[0][location]=somewhere&e[0][description]=somedesc2 HTTP/1.1
> Host: addtocalendar.com
> User-Agent: curl/7.51.0
> Accept: */*
> Referer: http://www.google.at
> 
< HTTP/1.1 302 Found
< Server: nginx
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Cache-Control: no-cache
< Date: Wed, 30 Nov 2016 18:14:12 GMT
< Location: https://www.google.com/calendar/render?action=TEMPLATE&dates=20161129T230000Z/20161203T100000Z&location=somewhere&text=some+title&details=somedesc2%0A%0A--%0Ahttp%3A%2F%2Fgo.addtocalendar.com
< Set-Cookie: m=rB8YsVg/FvSufkiLTFGcAg==; expires=Thu, 30-Nov-17 18:14:12 GMT; path=/
< 
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="refresh" content="1;url=https://www.google.com/calendar/render?action=TEMPLATE&amp;dates=20161129T230000Z/20161203T100000Z&amp;location=somewhere&amp;text=some+title&amp;details=somedesc2%0A%0A--%0Ahttp%3A%2F%2Fgo.addtocalendar.com" />

        <title>Redirecting to https://www.google.com/calendar/render?action=TEMPLATE&amp;dates=20161129T230000Z/20161203T100000Z&amp;location=somewhere&amp;text=some+title&amp;details=somedesc2%0A%0A--%0Ahttp%3A%2F%2Fgo.addtocalendar.com</title>
    </head>
    <body>
        Redirecting to <a href="https://www.google.com/calendar/render?action=TEMPLATE&amp;dates=20161129T230000Z/20161203T100000Z&amp;location=somewhere&amp;text=some+title&amp;details=somedesc2%0A%0A--%0Ahttp%3A%2F%2Fgo.addtocalendar.com">https://www.google.com/calendar/render?action=TEMPLATE&amp;dates=20161129T230000Z/20161203T100000Z&amp;location=somewhere&amp;text=some+title&amp;details=somedesc2%0A%0A--%0Ahttp%3A%2F%2Fgo.addtocalendar.com</a>.
    </body>
```

I don't see any reason for this in at least in the gmail calendar variant - other then sitting in MITM position

**Comment by elie222** [comment]
So let's fork this package and make one that doesn't put their server in
the middle.

**Comment by birdspider** [comment]
@elie222 : I'm pretty much done (features that I need), I'll post here when I have something to show/tested/uploaded.

**Comment by jamesonnuss** [comment]
@elie222 @birdspider Thank you. I am still trying to find an alternative. Looking forward to your post.

**Comment by blcarson** [comment]
+1 for this. Also need to add an all-day option so clients dont see crap like this:

![screenshot 1](https://cloud.githubusercontent.com/assets/1023153/20816490/628be5aa-b7d7-11e6-92a7-fb3236f24065.jpg)

**Comment by birdspider** [comment]
@elie222 there you go https://github.com/birdspider/calendarium
@blcarson done for google and ics 

beware - for ics (Outlook, Thunderbird) you'll need to implement your own backend

**Comment by blcarson** [comment]
@birdspider Awesome! Will look into this more over the weekend. If you need any help with styling and whatnot let me know - would be happy to help.

**Comment by birdspider** [comment]
@blcarson I has basicly no styles yet, just a minimal set and a "plain" mode to make I a bit nicer, I do not plan to provide extensive extra styling but contributions are welcome.

**Comment by atc-master** [comment]
The "http://go.addtocalendar.com" link just tells users about the widget. Nothing special.

**Comment by elie222** [comment]
But why would someone want that in the invite?
Not sure why you feel it's necessary for users to see an ad from this repo
on each calendar event, and I'm not too sure what you aim to get from it
either. People that want a calendar widget will search for it and this repo
will show up high.

**Comment by atc-master** [comment]
@elie222 this is like a logo. You use Github and you see Octocat everywhere. You buy coffe in Starbucks and you see Starbucks logo everywhere. Look at your phone. What you see? Logo.

But why you so fear the widget website "logo" in the event description?

**Comment by elie222** [comment]
No it's not like that. It's like creating a react app and seeing fb
branding over it. Or an angular one and seeing Google branding.

It's up to you what you do, but I'm not using this package because of this
issue. And a lot of others won't either. It's up to you if you care about
that or not. I would recommend sticking it in the readme so that you don't
waste people's time.

**Comment by sigmatec** [comment]
I understand that you don't want it elie, and neither do I, but I also think it's unfair to expect the creators of this not to receive some credit for their work. The widget is using code on their server to generate the ICS files, so you are using THEIR resources for free, and you're still complaining about a bit of branding? Either build your own widget, or re-assess your sense of entitlement.

**Comment by elie222** [comment]
It's not a sense of entitlement. I gave my feedback and said I won't use
it. That's about it.

And I still think the branding is sort of ridiculous and not really sure
what the game plan is. If it was a paid service I'd get it. Pay or see the
branding. But that doesn't seem to be an option.

**Comment by atc-master** [comment]
@elie222 how much money you suggest/could pay for remove the tagline?

@sigmatec is right. AddToCalendar is a very simple to use solution for end user. The generation process is encapsulated in backend and we support it. The idea of tag line is just tell users about us.

But I understand @elie222. When you get the package from github you should know about this behavior. We have task for review and actualization our github repository after long time of freeze.

**Comment by elie222** [comment]
If you actually wanted to turn it into a business then I'd look at the
competition see what they're pricing and charge a similar amount.

I don't know how the big market for this is, but you could also charge by
number of events sent each month. 1000 events are free. 10k cost 100
dollars. Etc. I made that up. But that's the general pricing structure you
see for things like this.

**Comment by Renrhaf** [comment]
Agreed with @elie222 that it should be written somewhere because my team and I, are using it on a new website and now the client complains about this "ad". So I need to switch to an other solution, unfortunately...

**Comment by zaisahil** [comment]
Is there any other solution ? Or a way to remove this? Please help! I am stuck very badly and can't find some other free version with such facilities.

**Comment by atc-master** [comment]
@zaisahil please write to support@addtocalendar.com

**Comment by elie222** [comment]
@zaisahil yes. This was posted below:
https://github.com/birdspider/calendarium

**Comment by elie222** [comment]
I made an update to the README so that others don't waste their time if they don't want addtocalendar.com in their events:
https://github.com/AddToCalendar/addtocalendar/pull/38/files

**Comment by atc-master** [comment]
@elie222 I've changed the README according your comments. Please take a look.

**Comment by rruprai** [comment]
Looks like addtocalendar has merged with AddEvents. I have found that if you do a custom solution, the link will not be in the `.ics` file. 

Here is an example [(link)](https://www.addevent.com/add-to-calendar-button) 

```
<!-- AddEvent script -->
<script type="text/javascript" src="https://addevent.com/libs/atc/1.6.1/atc.min.js" async defer></script>

<!-- Button code -->
<div title="Add to Calendar" class="addeventatc">
    Add to Calendar
    <span class="start">09/06/2018 08:00 AM</span>
    <span class="end">09/06/2018 10:00 AM</span>
    <span class="timezone">America/Los_Angeles</span>
    <span class="title">Summary of the event</span>
    <span class="description">Description of the event</span>
    <span class="location">Location of the event</span>
</div>
```
