### ISSUE TITLE
Is NPM up to date? Error: addtocalendar.load is not a function

### ISSUE THREAD

**Issue by MiMaMuh** [AddToCalendar/addtocalendar#26]
Hi,

i installed the addtocalendar package from npm with version 1.5.3. But I ran into the error "addtocalendar.load is not a function" like mentioned in pull-request #11. After looking into the npm code in my node_modules folder I figured out that it isn't the same code like on github and I ran into the issue because then load function there is:
```js
addtocalendar.load = ready(function () {
```

But in the up to date code on github it is:
```js
addtocalendar.load = function () {
```
So it has to fail because the ready() function do not return anything.

So my honest question is: Is this project still in active development? Or why is the code on github signed with version 1.5.3, the npm version is also on 1.5.3 but the code is different?

**Comment by KingKarrow** [comment]
I'm seeing this too, but with the Bower package. I also realize the Bower package is a separate repo? Not sure why.

In this repo, it looks like there was a commit to `addtocalendar.js` recently, but `addtocalendar.min.js` (and the js in the bower repo) was last updated months ago.

**Comment by mattgrande** [comment]
I'm getting this error as well... @atc-master, anything you can do about this?

**Comment by rakelblujeans** [comment]
bump

**Comment by sigmatec** [comment]
Yeah, it still hasn't been updated. Just wasted an hour trying to figure out why this wasn't working.

**Comment by atc-master** [comment]
Fixed.

**Comment by dosercz** [comment]
npm package is still not updated:(

**Comment by htmled** [comment]
I'm getting the same thing.
