### ISSUE TITLE
Outlook Time Zone

### ISSUE THREAD

**Issue by pipbeard** [AddToCalendar/addtocalendar#3]
Outlook assumes incoming events are in UTC, and subtracts for local time, causing the events to show at the wrong time.  All other calendars (Google, iCal, Yahoo) work great!

I'd be happy to contribute code to fix this problem -- I think if just the event generator for Outlook were to convert the entered time (`date_start` & `date_end`) to UTC, that would fix it.

I'm guessing that's how https://addthisevent.com/ gets around it.

**Comment by theblockmonkey** [comment]
Having the same issue - has there been any fix for this?

**Comment by firewaller** [comment]
+1

**Comment by atc-master** [comment]
Fixed.
