### ISSUE TITLE
Can I remove the credit at the bottom with your url??

### ISSUE THREAD

**Issue by rvizcaino80** [AddToCalendar/addtocalendar#30]
I am working on an important project and it is not good to have your url inside the description of the event, so I want to remove it. My client do not have any issue paying for your product. This is possible?

**Comment by sigmatec** [comment]
We would also be willing to pay to have this removed, depending on price.  Maybe offer a premium version?

**Comment by zenics** [comment]
+1 here

**Comment by zenics** [comment]
it would be nice to add a custom url for the event

**Comment by aske-cph** [comment]
Seriously this plugin is useless with this link. Also willing to pay but this is just dumb. Also they don't even say that they plug anywhere...

**Comment by riggaccess** [comment]
Its a great plugin but completely useless with that link at the bottom, not a nice surprise as others have mentioned. Is there any way to remove it?

**Comment by TomRZaperoo** [comment]
bump..!

**Comment by albertofrecina** [comment]
Did you remove it?

**Comment by TomRZaperoo** [comment]
I couldn't see how to..I've emailed the vendor but had no reply..

**Comment by sigmatec** [comment]
You can't remove it, it is added server-side. Only the vendor can, if they choose to do so.

**Comment by TomRZaperoo** [comment]
Which is what I've been asking them, it appears this is no longer supported.

**Comment by atc-master** [comment]
# Please ask support@addtocalendar.com

**Comment by TomRZaperoo** [comment]
Yes, I already tried that, I sent an email to that address on 10 May 2017 16:42 and have still heard nothing back - any suggestions on what to do next?
