### ISSUE TITLE
Help API no longer working for recurring events

### ISSUE THREAD

**Issue by Nicholashuber** [AddToCalendar/addtocalendar#52]
Adding these params to my urls was working to create multiple events repeating daily as per directions from the developer over email. As of this year it seems to have stopped working. I cant seem to get in contact with the developer :( I've been going through older bower packages and the npm packages but I've found nothing. Is it possible these params are named differently? Any help or insight is appreciated.
`[google_repeat]=RRULE%3AFREQ%3DDAILY%3BUNTIL%3D20180309T114600Z%3BBYDAY%3DMO%2CTU%2CWE%2CTH%2CFR&e[0][ical_rec]=true&e[0][ical_rec_freq]=DAILY&e[0][ical_rec_until]=3/9/2018 23:59:59`

**Comment by atc-master** [comment]
@Nicholashuber I'm sorry about that but the AddToCalendar is a part of AddEvent.com. Please write to support@addevent.com
